spring:
  config:
    activate:
      on-profile: "real"
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://onlycamper.clbvjhbqwdz3.ap-northeast-2.rds.amazonaws.com:3306/only_camper
      username: lee36656
      password: 
#  flyway:
#    user: order-svc
#    password: order-pass
#    schemas: order
#    url: jdbc:mysql://localhost:3306/order?serverTimezone=UTC&characterEncoding=UTF-8
#    enabled: true