#default-local
spring:
  profiles:
    include: "oauth"
    group:
      "real": "real-db"
  config:
    import:
      - classpath:aws.yml
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10

logging.level.org.hibernate.SQL: debug
example:
  gift:
    base-url: http://localhost:18080/
