server:
  shutdown: graceful

spring:
#  web:
#    resources:
#      static-locations: classpath:/static
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    #    database-platform: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true #시스템아웃으로 표기 시(비추천)
        format_sql: true
#        use_sql_comments : true #jpql 로그볼 시
        default_batch_fetch_size: 100 #in 절을 사용하겠다는 설정이며 in 절에 들어갈 갯수 설정

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/order?serverTimezone=UTC&characterEncoding=UTF-8
      username: order-svc
      password: order-pass
  flyway:
    user: order-svc
    password: order-pass
    schemas: order
    url: jdbc:mysql://localhost:3306/order?serverTimezone=UTC&characterEncoding=UTF-8
    enabled: true

#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true
#  thymeleaf:
#    cache: false

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

logging:
  config: classpath:logback-local.xml
  level: #logger를 통해서 볼때 (추천)
    org.hibernate.SQL: debug
    org.hibernate.type: trace #쿼리 인자값 보기

# aws 의 access-key, secret-key 를 반영해야 정상 동작함
cloud:
  aws:
    access-key: AKIAZ6DIH2TO4G6LDAKD
    secret-key: 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